on:
  push:
    branches:
      - master

jobs:
  build:
    runs on: ubuntu-latest

    steps:
      - name: "Testing git hup actions"
        run: pwd

      - name: "Testing printing"
        run: echo ahmed
