on:
  push:
    branches:
      - master

jobs:
  build:
    runs on: ubuntu-latest

    steps:
      - uses: action/checkout@v3

      - name: "login to ducker hup"
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --passwoed ${{ secrets.DOCKER_TOCKEN }}
